%let token1=CAACEdEose0cBAG7fjIkflwbvxseGsbEUNgebTjVtVCzBTPJq6Fsf3tZBkOFNGe6sCZCLn1HZAtL;
%let token2=ZAfKJBToo0bxAP8IcUqM3ZBCwIAijUwzCwLvZAorpTagMZA9QqRTnphWAXQCmrW2ZCHMuZAQqZBw;
%let token3=FE7IO3tZBLMexau7dGNRh6CRs2GRuKZApPEGEppht8FjsjiRpDAl9jANsZAQZDZD;
%let token=&token1.&token2.&token3;
%put TOKEN ADDED;
